name: push-workflow
on: push

jobs:
  push-job: 
    runs-on: ubuntu-latest
    steps: 
    - name: step1
      run: echo hello world
   - name: step2
      run: echo this is test code3
      
       
