name: push-workflow
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo step1!!
      - name: step2
        run: |
          echo step2!!
          echo github action
