name: pull-request-workflow
on: pull_request

jobs:
  pusll-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo step1!!
      - name: step2
        run: |
          echo step2!!
          echo github action
