name: pull_request-workflow
on: 
    pull_request:
        types: [opened]

jobs:
    pull-request-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo hellow1
            - name: step2
              run : echo hellow2
            - name: step3
              run:
                echo hellow world1
                echo hellow world2!
