name: pull-request-workflow-1
on: pull_request

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hellow world
      - name: step2
        run: |
          echo hellow world
          echo github action
