name: pull-request-workflow 3 3 3 
on: 
  pull_request:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run:
        echo hello world
        echo github action

