name: push-workflow
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hellow world
      - name: step2
        run: |
          echo hellow world
          echo github action
