name: push-workflow

on: push 
jobs:                          
    push-jobs:                  
        runs-on: ubuntu-latest  
        steps:                  
        - name: step1
        run: echo hello world
